// <auto-generated />
using EchoBot1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EchoBot1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230807162004_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EchoBot1.Models.TeamMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("MemberName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            MemberName = "Member 1"
                        },
                        new
                        {
                            MemberId = 2,
                            MemberName = "Member 2"
                        },
                        new
                        {
                            MemberId = 3,
                            MemberName = "Member 3"
                        },
                        new
                        {
                            MemberId = 4,
                            MemberName = "Member 4"
                        },
                        new
                        {
                            MemberId = 5,
                            MemberName = "Member 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
